"const fs = require('fs');"  
"const path = require('path');"  
""  
"function writeFile(filePath, content) {"  
"  fs.writeFileSync(filePath, content);"  
"  console.log('Created:', filePath);"  
"}"  
""  
"module.exports = { writeFile };" 
